Let's import the Pandas library

In [1]:
import pandas as pd

Let's load a dataset containing information about restaurants available on the Swiggy food delivery platform. Note that this data is compiled by third-party sources and isn't affiliated with Swiggy or any of the mentioned restaurants.

In [2]:
df = pd.read_csv('swiggy.csv')
df.head()

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63

In [5]:
df = pd.read_csv('swiggy.csv', index_col = 'ID')
df.head()

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
ID,,,,,,,,,
211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8680 entries, 211 to 466488
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Area           8680 non-null   object
 1   City           8680 non-null   object
 2   Restaurant     8680 non-null   object
 3   Price          8680 non-null   float64
 4   Avg ratings    8680 non-null   float64
 5   Total ratings  8680 non-null   int64
 6   Food type      8680 non-null   object
 7   Address        8680 non-null   object
 8   Delivery time  8680 non-null   int64
dtypes: float64(2), int64(2), object(5)
memory usage: 678.1+ KB

The 'Price' column denotes the average food prices at the restaurant. The 'Delivery time' column denotes the average delivery times at the restaurant.

Let's begin by finding all restaurants with an average rating that is 4.0 or higher.

In [7]:
df['Avg ratings'] >= 4.0

ID
211        True
221        True
246        True
248       False
249        True
          ...
464626    False
465835    False
465872    False
465990    False
466488    False
Name: Avg ratings, Length: 8680, dtype: bool

In [8]:
df[df['Avg ratings'] >= 4.0]

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
ID,,,,,,,,,
211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63
254,Indiranagar,Bangalore,Treat,800.0,4.5,100,"Mughlai,North Indian",100 Feet Road,56
...,...,...,...,...,...,...,...,...,...
442347,Lake Town,Kolkata,Savister,250.0,4.3,20,"Snacks,Beverages",Lake Town,87
444297,Vastrapur,Ahmedabad,Chup Chaap,200.0,4.8,20,"Indian,Tandoor,Beverages,North Indian,Chinese,...",Vastrapur,52
446079,Vastrapur,Ahmedabad,Rotlo Gujarati Rasthal,300.0,4.2,20,Gujarati,Vastrapur,47
448359,Vastrapur,Ahmedabad,P Se Pavbhaji,150.0,4.4,20,"Street Food,Fast Food,Combo,Snacks,Beverages,D...",Vastrapur,50
450543,Perambur,Chennai,Afresh,100.0,5.0,20,"Healthy Food,Salads,Desserts,Beverages",Perambur,50

Let's restrict this to restaurants that have at least 500 ratings

In [9]:
df[(df['Avg ratings'] >= 4.0) & (df['Total ratings'] >= 500)]

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
ID,,,,,,,,,
258,Indiranagar,Bangalore,Chinita Real Mexican Food,1000.0,4.5,500,"Mexican,Beverages,Salads",Double Road,53
308,Koramangala,Bangalore,Bangaliana,300.0,4.0,500,Bengali,7Th Block,57
446,Cooke Town,Bangalore,Altaf'S Chillies Restaurants,250.0,4.3,500,"North Indian,Chinese",Cooke Town,55
1050,Jayanagar,Bangalore,Nagarjuna Chimney,800.0,4.2,1000,"Seafood,Andhra,Biryani,South Indian,Combo,Dess...",3Rd Block,48
1547,Masab Tank,Hyderabad,Dine Hill,400.0,4.1,500,"Arabian,Biryani,North Indian,Chinese",Ahmed Nagar,49
...,...,...,...,...,...,...,...,...,...
395439,Adajan,Surat,Shree Kathiyawadi Khadki,250.0,4.3,1000,"Gujarati,Thalis,North Indian,Rajasthani,Desser...",Adajan,46
395519,Himayath Nagar,Hyderabad,Wahh Chaap,300.0,4.1,500,"North Indian,Biryani",Himayath Nagar,31
395927,Hatibagan,Kolkata,Nic Natural Ice Creams,120.0,4.8,500,"Ice Cream,Desserts",Arabinda Sarani,37
397744,Nsp,Delhi,Modern Caterers,300.0,4.2,1000,"North Indian,Chinese,Snacks,Beverages,Punjabi",Nsp,46
399576,Kondhwa,Pune,Jyoti Restaurant,200.0,4.1,1000,"North Indian,South Indian,Beverages,Ice Cream,...",Kondhwa,62

Let's find fast and affordable restaurants which have a delivery time of less than 30 minutes and a price point of less than 300

In [10]:
df[(df['Delivery time'] < 30) & (df['Price'] < 300)]

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
ID,,,,,,,,,
6745,Koti,Hyderabad,Tibbs Frankie,150.0,4.3,100,Snacks,Hanuman Tekdi Road,29
6851,Abids,Hyderabad,Agrawala Sweets,250.0,4.3,100,"Sweets,Fast Food",Jn Road,27
9757,Pitam Pura,Delhi,Shut Up & Eat,250.0,4.1,100,Indian,Nsp,27
12434,Mumbai,Mumbai,J.J Jalebi,100.0,3.6,500,"Desserts,Sweets",Lbs Marg,25
32003,Himayatnagar,Hyderabad,Rice Bowl,200.0,4.0,1000,"North Indian,South Indian",Urdu Galli,28
...,...,...,...,...,...,...,...,...,...
366790,Jam Bagh,Hyderabad,Subbu Mirchi Point,100.0,4.1,100,"Street Food,Indian,Snacks",Kachiguda,29
372444,Gulbai Tekra,Ahmedabad,New Girish Coldrinks,200.0,4.1,50,"Juices,Beverages,Desserts",Paldi & Ambawadi,27
382460,Himayath Nagar,Hyderabad,Venkateshwara Fast Food,150.0,3.9,100,"Indian,Chinese,South Indian",Himayath Nagar,27
465835,Rohini,Delhi,Jay Mata Ji Home Kitchen,200.0,2.9,80,South Indian,Rohini,28
465990,Rohini,Delhi,Shree Ram Paratha Wala,150.0,2.9,80,"North Indian,Indian,Snacks",Rohini,28

Let's view just the restaurant names, city, and average ratings of the restaurants obtained in our previous query

In [11]:
df[(df['Delivery time'] < 30) & (df['Price'] < 300)][['Restaurant', 'City', 'Avg ratings']]

                      Restaurant       City  Avg ratings
ID
6745               Tibbs Frankie  Hyderabad          4.3
6851             Agrawala Sweets  Hyderabad          4.3
9757               Shut Up & Eat      Delhi          4.1
12434                 J.J Jalebi     Mumbai          3.6
32003                  Rice Bowl  Hyderabad          4.0
...                          ...        ...          ...
366790        Subbu Mirchi Point  Hyderabad          4.1
372444      New Girish Coldrinks  Ahmedabad          4.1
382460   Venkateshwara Fast Food  Hyderabad          3.9
465835  Jay Mata Ji Home Kitchen      Delhi          2.9
465990    Shree Ram Paratha Wala      Delhi          2.9

[94 rows x 3 columns]

In [32]:
df.loc[(df['Delivery time'] < 30) & (df['Price'] < 300), ['Restaurant', 'City', 'Avg ratings']]

Empty DataFrame
Columns: [Restaurant, City, Avg ratings]
Index: []

Let's find restaurants in the Koramangala region that serve Chinese cuisine

In [31]:
df[(df['Area'] == 'Koramangala') & (df['Food type'].str.contains('Chinese'))]

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time,Detailed address available
ID,,,,,,,,,,
211,Koramangala,Bangalore,Tandoor Hut,255.00,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,69,True
435,Koramangala,Bangalore,Bamey'S Restro Cafe,340.00,4.4,100,"Chinese,Thai,Nepalese",5Th Block,66,True
18981,Koramangala,Bangalore,Sultans Of Spice,509.15,4.3,50,"North Indian,Chinese,Biryani",Koramangala 5Th Block,70,True
19172,Koramangala,Bangalore,30 Square,300.00,2.9,80,Chinese,Khb Colony 5Th Block,74,True
25222,Koramangala,Bangalore,China Pearl,935.00,4.5,1000,"Chinese,Asian",6Th Block,74,True
28570,Koramangala,Bangalore,Royal Treat,164.05,4.1,500,"North Indian,Chinese,Seafood,Biryani",5Th Block Koramangala,64,True
30732,Koramangala,Bangalore,The Rendezvous,510.00,4.0,20,"Continental,Italian,Indian,Chinese",80Ft Road Koramangala,80,True
31698,Koramangala,Bangalore,Little Kolkata,255.00,4.1,20,"North Indian,Bengali,Chinese",5Th Block,69,True
36862,Koramangala,Bangalore,Dice N Dine,425.00,4.0,500,"American,Asian,Chinese,Continental,Desserts,It...",Jyothi Nivas College Road,67,True
56233,Koramangala,Bangalore,Khawa Karpo,151.30,4.6,100,Chinese,Koramangala,63,False
61790,Koramangala,Bangalore,Sardarji Londonwaley,297.50,4.0,500,"Indian,North Indian,Punjabi,Chinese,Biryani",Koramangala,65,False
81944,Koramangala,Bangalore,Nasi And Mee,1020.00,4.6,100,"Pan-Asian,Singaporean,Malaysian,Japanese,Asian...",Koramangala,71,False
131864,Koramangala,Bangalore,Kerala Food Club,212.50,4.2,500,"Kerala,Chinese,Biryani,Seafood,South Indian",Nanjappa Layout,62,True
151036,Koramangala,Bangalore,Punjabi Unplugged,300.00,3.9,500,"North Indian,Chinese,Indian,Mughlai",Koramangala 1St Block,64,True
163740,Koramangala,Bangalore,Darjeeling Hot Momos,212.50,4.2,100,Chinese,Koramangala,62,False
175907,Koramangala,Bangalore,Kitchens Of China,350.00,2.9,80,"Chinese,Combo,Asian",Koramangala,66,False
192029,Koramangala,Bangalore,Tibetan Mother'S Kitchen,212.50,4.1,500,"Chinese,Tibetan,Thai",Koramangala,61,False
254870,Koramangala,Bangalore,Paratha Experiment,170.00,4.3,50,"North Indian,Punjabi,Home Food,Indian,Snacks,C...",Nanjappa Reddy Layout Koramangala,62,True
284774,Koramangala,Bangalore,Biergarten Brewery & Kitchen,637.50,4.1,100,"Continental,Pizzas,North Indian,Chinese,Asian,...",Koramangala,72,False
291520,Koramangala,Bangalore,Xoox Brewmill,425.00,4.5,20,"North Indian,Chinese,Pizzas,Continental,Desser...",Koramangala,74,False
307050,Koramangala,Bangalore,Call Me Chow,340.00,4.3,1000,"Chinese,Pan-Asian",Near Licious Koramangala Hub,66,True
310253,Koramangala,Bangalore,Globo Combo,300.00,2.9,80,"Chinese,North Indian,Combo",Koramangala,68,False
316928,Koramangala,Bangalore,Hungry Chang,280.00,3.8,100,"Chinese,Fast Food,Pan-Asian,Combo",Koramangala,67,False
328099,Koramangala,Bangalore,Ancient Chinese House,255.00,4.1,100,Chinese,Koramangala,72,False
328971,Koramangala,Bangalore,Chuckling Chinese,255.00,4.1,100,"Chinese,Fast Food",Koramangala,73,False
329149,Koramangala,Bangalore,Imperio Restaurant,300.00,3.9,100,"Biryani,Mughlai,North Indian,Tandoor,Kerala,Ch...",Koramangala,66,False
335651,Koramangala,Bangalore,Wok & Talk,300.00,2.9,80,Chinese,Koramangala,71,False
336463,Koramangala,Bangalore,Chinese Bistro,200.00,2.9,80,"Chinese,Biryani",Koramangala,73,False
345726,Koramangala,Bangalore,Chinese Kitchen,255.00,4.1,500,"Chinese,Indian",Koramangala,75,False
382537,Koramangala,Bangalore,Singh Da Punjabi Dhaba,200.00,3.8,100,"Punjabi,Tandoor,Chinese",Koramangala,64,False
392828,Koramangala,Bangalore,Big Bowl Company,212.50,4.1,100,"North Indian,Chinese,Biryani,Fast Food",Koramangala,63,False
393402,Koramangala,Bangalore,Friends Euro Restaurant,599.00,2.9,80,"Chinese,Continental,Indian,Fast Food",Koramangala,75,False
393835,Koramangala,Bangalore,The Momo Co.,250.00,3.8,50,"Chinese,Pan-Asian,Tibetan",Koramangala,65,False
414306,Koramangala,Bangalore,Food Court By Kitchens@,450.00,2.9,80,"North Indian,Biryani,Chinese,Mughlai,Seafood,S...",Koramangala,78,False
415302,Koramangala,Bangalore,Juno,300.00,2.9,80,"Pan-Asian,Oriental,Chinese,Indian,Persian",Koramangala,78,False
429004,Koramangala,Bangalore,Shehzadas Biryani,297.50,4.2,20,"Biryani,Hyderabadi,Andhra,North Indian,South I...",Koramangala,76,False
437891,Koramangala,Bangalore,Baba Chill,500.00,2.9,80,"North Indian,Chinese,Fast Food",Koramangala,66,False
438411,Koramangala,Bangalore,Lepcha Darjeeling Momos,150.00,2.9,80,Chinese,Koramangala,68,False
107301,Koramangala,Bangalore,Yum In My Tum,200.00,3.9,500,"Chinese,Continental,Beverages,Pizzas,Italian,N...",Koramangala,64,False
366890,Koramangala,Bangalore,Hokart - Special Hot Momos,127.50,4.3,50,"Fast Food,Street Food,Snacks,Chinese",Koramangala,57,False

What if we wanted restaurants in Koramangala which exclusively serve Chinese cuisine?

In [15]:
df[(df['Area'] == 'Koramangala') & (df['Food type'].str.contains('Chinese')) & (~df['Food type'].str.contains(','))]

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
ID,,,,,,,,,
19172,Koramangala,Bangalore,30 Square,300.0,2.9,80,Chinese,Khb Colony 5Th Block,64
56233,Koramangala,Bangalore,Khawa Karpo,178.0,4.6,100,Chinese,Koramangala,53
163740,Koramangala,Bangalore,Darjeeling Hot Momos,250.0,4.2,100,Chinese,Koramangala,52
328099,Koramangala,Bangalore,Ancient Chinese House,300.0,4.1,100,Chinese,Koramangala,62
335651,Koramangala,Bangalore,Wok & Talk,300.0,2.9,80,Chinese,Koramangala,61
438411,Koramangala,Bangalore,Lepcha Darjeeling Momos,150.0,2.9,80,Chinese,Koramangala,58

There's been a lot of complaints about restaurants not serving their food on time. We want to increase the delivery time by five minutes to account for any possible delays. Note that the following operation will modify our DataFrame.

In [17]:
df['Delivery time'] += 5

Let's run our previous filtering query to inspect these changes

In [18]:
df[(df['Area'] == 'Koramangala') & (df['Food type'].str.contains('Chinese')) & (~df['Food type'].str.contains(','))]

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
ID,,,,,,,,,
19172,Koramangala,Bangalore,30 Square,300.0,2.9,80,Chinese,Khb Colony 5Th Block,74
56233,Koramangala,Bangalore,Khawa Karpo,178.0,4.6,100,Chinese,Koramangala,63
163740,Koramangala,Bangalore,Darjeeling Hot Momos,250.0,4.2,100,Chinese,Koramangala,62
328099,Koramangala,Bangalore,Ancient Chinese House,300.0,4.1,100,Chinese,Koramangala,72
335651,Koramangala,Bangalore,Wok & Talk,300.0,2.9,80,Chinese,Koramangala,71
438411,Koramangala,Bangalore,Lepcha Darjeeling Momos,150.0,2.9,80,Chinese,Koramangala,68

For future verification purposes, let's save this query as a mask

In [20]:
(df['Area'] == 'Koramangala') & (df['Food type'].str.contains('Chinese')) & (~df['Food type'].str.contains(','))

ID
211       False
221       False
246       False
248       False
249       False
          ...
464626    False
465835    False
465872    False
465990    False
466488    False
Length: 8680, dtype: bool

In [21]:
# Mask the query for reusability
mask = (df['Area'] == 'Koramangala') & (df['Food type'].str.contains('Chinese')) & (~df['Food type'].str.contains(','))

There's a platform-wide discount running for restaurants rated 4.0 or higher. Let's discount all prices by 15%.

In [33]:
#df.loc['Avg ratings' >= 4.0, 'Price'] *= 0.85  # why won't this work?

In [34]:
df.loc[df['Avg ratings'] >= 4.0, 'Price']

ID
211       255.0
221       255.0
246       552.5
249       297.5
254       680.0
          ...
442347    212.5
444297    170.0
446079    255.0
448359    127.5
450543     85.0
Name: Price, Length: 4005, dtype: float64

In [35]:
df.loc[df['Avg ratings'] >= 4.0, 'Price'] *= 0.85

In [36]:
df[mask]

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time,Detailed address available
ID,,,,,,,,,,
19172,Koramangala,Bangalore,30 Square,300.000,2.9,80,Chinese,Khb Colony 5Th Block,74,True
56233,Koramangala,Bangalore,Khawa Karpo,128.605,4.6,100,Chinese,Koramangala,63,False
163740,Koramangala,Bangalore,Darjeeling Hot Momos,180.625,4.2,100,Chinese,Koramangala,62,False
328099,Koramangala,Bangalore,Ancient Chinese House,216.750,4.1,100,Chinese,Koramangala,72,False
335651,Koramangala,Bangalore,Wok & Talk,300.000,2.9,80,Chinese,Koramangala,71,False
438411,Koramangala,Bangalore,Lepcha Darjeeling Momos,150.000,2.9,80,Chinese,Koramangala,68,False

Let's create a new column to indicate if a restaurant has an 'Address' which is different from its 'Area'. Let's call this 'Detailed address available'.

In [37]:
df['Detailed address available'] = df['Area'] != df['Address']

In [38]:
df[mask]

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time,Detailed address available
ID,,,,,,,,,,
19172,Koramangala,Bangalore,30 Square,300.000,2.9,80,Chinese,Khb Colony 5Th Block,74,True
56233,Koramangala,Bangalore,Khawa Karpo,128.605,4.6,100,Chinese,Koramangala,63,False
163740,Koramangala,Bangalore,Darjeeling Hot Momos,180.625,4.2,100,Chinese,Koramangala,62,False
328099,Koramangala,Bangalore,Ancient Chinese House,216.750,4.1,100,Chinese,Koramangala,72,False
335651,Koramangala,Bangalore,Wok & Talk,300.000,2.9,80,Chinese,Koramangala,71,False
438411,Koramangala,Bangalore,Lepcha Darjeeling Momos,150.000,2.9,80,Chinese,Koramangala,68,False

Let's find the average of 'Delivery time' across all restaurants

In [77]:
df['Delivery time'].mean().round(2)

np.float64(63.97)

Let's make a new column 'Quality' to categorise each restaurant based on their ratings, using the criteria
*   'Excellent' if the average rating is at least 4.5
*   'Good' if the average rating is at least 4.0 but less than 4.5
*   'Average' if the average rating is at least 3.0 but less than 4.0
*   'Poor' if the average rating is less than 3.0

In [40]:
df['Avg ratings'] >= 4.5

ID
211       False
221       False
246       False
248       False
249       False
          ...
464626    False
465835    False
465872    False
465990    False
466488    False
Name: Avg ratings, Length: 8680, dtype: bool

In [58]:
df.loc[df['Avg ratings'] >= 4.5,  ['City', 'Area', 'Restaurant']]

             City         Area                 Restaurant
ID
254     Bangalore  Indiranagar                      Treat
258     Bangalore  Indiranagar  Chinita Real Mexican Food
2811    Bangalore  Ashok Nagar             Art Of Delight
3369    Bangalore  Ashok Nagar                   Truffles
5172       Mumbai  Bandra Area                  Theobroma
...           ...          ...                        ...
432094    Kolkata    Esplanade     Keventers Ice Creamery
440407    Kolkata    Lake Town             Hunger Twister
442032  Bangalore  Koramangala     Keventers Ice Creamery
444297  Ahmedabad    Vastrapur                 Chup Chaap
450543    Chennai     Perambur                     Afresh

[662 rows x 3 columns]

In [59]:
def categorise_quality(ratings_row):
    if ratings_row >= 4.5:
        return 'Excellent'
    elif ratings_row >= 4.0:
        return 'Good'
    elif ratings_row >= 3.0:
        return 'Average'
    else:
        return 'Poor'

In [60]:
df['Avg ratings']

ID
211       4.4
221       4.1
246       4.4
248       3.9
249       4.0
         ...
464626    2.9
465835    2.9
465872    2.9
465990    2.9
466488    2.9
Name: Avg ratings, Length: 8680, dtype: float64

In [62]:
#categorise_quality(df['Avg ratings'])  # why won't this work?

In [ ]:
# df['Quality']

In [63]:
df['Quality'] = df['Avg ratings'].apply(categorise_quality)

In [ ]:
df['Quality']

In [64]:
df[mask]

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time,Detailed address available,Quality
ID,,,,,,,,,,,
19172,Koramangala,Bangalore,30 Square,300.000,2.9,80,Chinese,Khb Colony 5Th Block,74,True,Poor
56233,Koramangala,Bangalore,Khawa Karpo,128.605,4.6,100,Chinese,Koramangala,63,False,Excellent
163740,Koramangala,Bangalore,Darjeeling Hot Momos,180.625,4.2,100,Chinese,Koramangala,62,False,Good
328099,Koramangala,Bangalore,Ancient Chinese House,216.750,4.1,100,Chinese,Koramangala,72,False,Good
335651,Koramangala,Bangalore,Wok & Talk,300.000,2.9,80,Chinese,Koramangala,71,False,Poor
438411,Koramangala,Bangalore,Lepcha Darjeeling Momos,150.000,2.9,80,Chinese,Koramangala,68,False,Poor

Let's try making another function do to the same thing. However, this time, we will change how the function works internally.

In [65]:
def categorise_quality_2(row):
    if row['Avg ratings'] >= 4.5:
        return 'Excellent'
    elif row['Avg ratings'] >= 4.0:
        return 'Good'
    elif row['Avg ratings'] >= 3.0:
        return 'Average'
    else:
        return 'Poor'

In [67]:
#df['Quality 2'] = df['Avg ratings'].apply(categorise_quality_2)  # why won't this work?

In [69]:
#df['Quality 2'] = df.apply(categorise_quality_2)  # why won't this work?

In [70]:
# This is the way to pass complete row by using axis = 1
df['Quality 2'] = df.apply(categorise_quality_2, axis = 1)

In [71]:
df[mask]

,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time,Detailed address available,Quality,Quality 2
ID,,,,,,,,,,,,
19172,Koramangala,Bangalore,30 Square,300.000,2.9,80,Chinese,Khb Colony 5Th Block,74,True,Poor,Poor
56233,Koramangala,Bangalore,Khawa Karpo,128.605,4.6,100,Chinese,Koramangala,63,False,Excellent,Excellent
163740,Koramangala,Bangalore,Darjeeling Hot Momos,180.625,4.2,100,Chinese,Koramangala,62,False,Good,Good
328099,Koramangala,Bangalore,Ancient Chinese House,216.750,4.1,100,Chinese,Koramangala,72,False,Good,Good
335651,Koramangala,Bangalore,Wok & Talk,300.000,2.9,80,Chinese,Koramangala,71,False,Poor,Poor
438411,Koramangala,Bangalore,Lepcha Darjeeling Momos,150.000,2.9,80,Chinese,Koramangala,68,False,Poor,Poor

Let's count the unique number of words used in naming restaurants across our database

In [72]:
def unique_name_words(restaurant_name_series):
    restaurant_names = restaurant_name_series.str.split().sum()
    return len(set(restaurant_names))

In [76]:
print(type(df['Restaurant']))

<class 'pandas.core.series.Series'>

In [ ]:
# df['Restaurant'].apply(unique_name_words)  # why won't this work?

In [75]:
unique_name_words(df['Restaurant'])

6647